CREATE DATABASE RETAIL_DB;

CREATE SCHEMA RAW;

CREATE TABLE RAW_ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    AMOUNT NUMBER,
    ORDER_DATE TIMESTAMP
);
